name: Spring Boot App CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn clean compile package -DskipTests --file pom.xml
      working-directory: back/
