name: Spring Boot App CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'corretto'

    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore

    - name: Setup Maven
      uses: stCarolas/setup-maven@v.4.5
      with:
        maven-version: 4.0.0-alpha-5

    - name: Build with Maven
      run: mvn clean compile package -DskipTests --file pom.xml
      working-directory: back/

    - name: Kill process on Port:8060
      run: |
        if sudo lsof -Pi :8060 -sTCP:LISTEN -t >/dev/null ; then
          sudo kill $(sudo lsof -t -i:8060) || true
        fi

    - name: Execute JAR File
      run: |
        cd /home/ubuntu/actions-runner/_work/pipeline-back/pipeline-back/back/target
        java -jar demo-0.0.1-SNAPSHOT.jar > build.log 2>&1 &
      
      
      