name: Spring Boot App CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile package -DskipTests --file pom.xml
      working-directory: back/
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: appback
        path: back/target/demo-0.0.1-SNAPSHOT.jar

    