name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 4.0.0-alpha-5

      - name: Build with Maven
        run: mvn clean compile package -DskipTests --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-app:${{ github.sha }}
          build-args: |
            JAR_FILE=target/demo-0.0.1-SNAPSHOT.jar

      - name: Transfer Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IPV4_EC2 }}
          username: ${{ secrets.AWS_ACCESS_KEY }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: my-app:${{ github.sha }}
          target: /home/ubuntu/my-app

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IPV4_EC2 }}
          username: ${{ secrets.AWS_ACCESS_KEY }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/my-app
            docker run -d -p 8060:8060 my-app:${{ github.sha }}