name: Spring Boot App CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: corretto
          maven-version: 4.0.0
    - name: Build with Maven
      run: mvn clean compile package -DskipTests --file pom.xml
      working-directory: back/
